//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LoginMsgResponse.proto
namespace LoginMsgResponse
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginLog")]
  public partial class LoginLog : global::ProtoBuf.IExtensible
  {
    public LoginLog() {}
    
    private string _machineId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"machineId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string machineId
    {
      get { return _machineId; }
      set { _machineId = value; }
    }
    private int _mark;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mark
    {
      get { return _mark; }
      set { _mark = value; }
    }
    private int _channelId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"channelId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channelId
    {
      get { return _channelId; }
      set { _channelId = value; }
    }
    private string _mobileType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"mobileType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mobileType
    {
      get { return _mobileType; }
      set { _mobileType = value; }
    }
    private string _loginTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"loginTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string loginTime
    {
      get { return _loginTime; }
      set { _loginTime = value; }
    }
    private string _writeTime;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"writeTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string writeTime
    {
      get { return _writeTime; }
      set { _writeTime = value; }
    }
    private string _mobileBrandType;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"mobileBrandType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mobileBrandType
    {
      get { return _mobileBrandType; }
      set { _mobileBrandType = value; }
    }
    private string _mobileNum;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"mobileNum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mobileNum
    {
      get { return _mobileNum; }
      set { _mobileNum = value; }
    }
    private string _appVersion;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"appVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string appVersion
    {
      get { return _appVersion; }
      set { _appVersion = value; }
    }
    private string _expParam;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"expParam", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string expParam
    {
      get { return _expParam; }
      set { _expParam = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}