//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: base_challenge_msg_struct.proto
namespace Chengzi
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"base_info")]
  public partial class base_info : global::ProtoBuf.IExtensible
  {
    public base_info() {}
    
    private uint _uid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private long _room_card = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"room_card", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long room_card
    {
      get { return _room_card; }
      set { _room_card = value; }
    }
    private long _coin = default(long);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private long _safe_coin = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"safe_coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long safe_coin
    {
      get { return _safe_coin; }
      set { _safe_coin = value; }
    }
    private uint _vip = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"vip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint vip
    {
      get { return _vip; }
      set { _vip = value; }
    }
    private uint _safeboxstate = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"safeboxstate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint safeboxstate
    {
      get { return _safeboxstate; }
      set { _safeboxstate = value; }
    }
    private uint _clogin = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"clogin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint clogin
    {
      get { return _clogin; }
      set { _clogin = value; }
    }
    private uint _weeklogin = default(uint);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"weeklogin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint weeklogin
    {
      get { return _weeklogin; }
      set { _weeklogin = value; }
    }
    private uint _reward = default(uint);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint reward
    {
      get { return _reward; }
      set { _reward = value; }
    }
    private uint _bankrupt = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"bankrupt", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint bankrupt
    {
      get { return _bankrupt; }
      set { _bankrupt = value; }
    }
    private uint _head_icon = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"head_icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint head_icon
    {
      get { return _head_icon; }
      set { _head_icon = value; }
    }
    private uint _login_ip = default(uint);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"login_ip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint login_ip
    {
      get { return _login_ip; }
      set { _login_ip = value; }
    }
    private uint _all_login_days = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"all_login_days", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint all_login_days
    {
      get { return _all_login_days; }
      set { _all_login_days = value; }
    }
    private byte[] _head_icon_url = null;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"head_icon_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] head_icon_url
    {
      get { return _head_icon_url; }
      set { _head_icon_url = value; }
    }
    private string _curr_pwd = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"curr_pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string curr_pwd
    {
      get { return _curr_pwd; }
      set { _curr_pwd = value; }
    }
    private int _play_slot_machine_count = default(int);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"play_slot_machine_count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int play_slot_machine_count
    {
      get { return _play_slot_machine_count; }
      set { _play_slot_machine_count = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"seat_info")]
  public partial class seat_info : global::ProtoBuf.IExtensible
  {
    public seat_info() {}
    
    private uint _uid = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private byte[] _name = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _sex = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private long _coin = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private uint _chairid = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"chairid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint chairid
    {
      get { return _chairid; }
      set { _chairid = value; }
    }
    private uint _head_icon = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"head_icon", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint head_icon
    {
      get { return _head_icon; }
      set { _head_icon = value; }
    }
    private long _buyin = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"buyin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long buyin
    {
      get { return _buyin; }
      set { _buyin = value; }
    }
    private long _score = default(long);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long score
    {
      get { return _score; }
      set { _score = value; }
    }
    private uint _login_ip = default(uint);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"login_ip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint login_ip
    {
      get { return _login_ip; }
      set { _login_ip = value; }
    }
    private bool _is_ready = default(bool);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"is_ready", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_ready
    {
      get { return _is_ready; }
      set { _is_ready = value; }
    }
    private bool _is_leave = default(bool);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"is_leave", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_leave
    {
      get { return _is_leave; }
      set { _is_leave = value; }
    }
    private byte[] _head_icon_url = null;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"head_icon_url", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] head_icon_url
    {
      get { return _head_icon_url; }
      set { _head_icon_url = value; }
    }
    private bool _is_dealer = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"is_dealer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_dealer
    {
      get { return _is_dealer; }
      set { _is_dealer = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"game_data_info")]
  public partial class game_data_info : global::ProtoBuf.IExtensible
  {
    public game_data_info() {}
    
    private uint _game_type = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"game_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint game_type
    {
      get { return _game_type; }
      set { _game_type = value; }
    }
    private uint _win = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"win", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint win
    {
      get { return _win; }
      set { _win = value; }
    }
    private uint _lose = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lose", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint lose
    {
      get { return _lose; }
      set { _lose = value; }
    }
    private long _maxwin = default(long);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"maxwin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long maxwin
    {
      get { return _maxwin; }
      set { _maxwin = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _maxcard = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"maxcard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> maxcard
    {
      get { return _maxcard; }
    }
  
    private long _daywin = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"daywin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long daywin
    {
      get { return _daywin; }
      set { _daywin = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}